export const CHAT_MESSAGE = "CHAT_MESSAGE";
export const CHOOSE_CARD = "CHOOSE_CARD";
export const FETCH_BOARD = "FETCH_BOARD";
export const GENERATE_BOARD = "GENERATE_BOARD";
export const SEND_PLAYER_INFO = "SEND_PLAYER_INFO";
export const UPDATE_BOARD = "UPDATE_BOARD";
